fix(data): fix some unicode issue (#157)
* fix(data): fix some unicode issue

* fix: ensure data/articles/index.json is valid before commir

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -59,6 +59,12 @@ Data fetch:
         }
       done
 
+      # check articles index is valid
+      node "data/articles/index.json" > /dev/null || {
+        echo "Invalid JSON in data/articles/index.json"
+        exit 1
+      }
+
     - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
     - |
       echo "Commit files"
