ci(gitlab): add force publish (2

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -41,33 +41,55 @@ Data fetch:
     GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
     GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
     GIT_DEPTH: 4242
-  before_script:
-    - yarn --frozen-lockfile
-    - yarn global add npx
-    - apk update && apk add git
-    - git config user.name "Social Groovy Bot"
-    - git config user.email "45039513+SocialGroovyBot@users.noreply.github.com"
-    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
-    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
   script:
     - yarn data:update
+    - apk update && apk add git jq
     - |
-      if [[ -n "$(git status -s ./data)" ]]; then
-        echo "Files changed, checking JSON validity"
-        # Check JSON files
-        for filename in ./data/*\.json; do
-          node "$filename" > /dev/null || {
-            echo "Invalid JSON in $filename"
-            exit 1
-          }
-        done
-        echo "Commit files"
-        # Commit files
-        NOW=$(date +"%Y%m%d_%H%M")
-        git add data
-        git commit -m "feat(data): $NOW update"
-        git push --no-verify origin HEAD:master
-        npx semantic-release
-      else
+      if [[ -z "$(git status -s ./data)" ]]; then
         echo "Nothing changed"
+        exit ${CI_JOB_SKIP_EXIT_CODE:-0}
       fi
+    - |
+      echo "Files changed, checking JSON validity"
+      # Check JSON files
+      for filename in ./data/*\.json; do
+        node "$filename" > /dev/null || {
+          echo "Invalid JSON in $filename"
+          exit 1
+        }
+      done
+
+    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
+    - |
+      echo "Commit files"
+      # Commit files
+      NOW=$(date +"%Y%m%d_%H%M")
+      git add data
+      git commit -m "feat(data): $NOW update"
+      git push --no-verify origin HEAD:${CI_COMMIT_REF_NAME}
+    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
+    - yarn global add @semantic-release/changelog @semantic-release/exec @semantic-release/git
+      semantic-release
+    - $(yarn global bin)/semantic-release
+
+Force Publish:
+  <<: *node_stage
+  only:
+    - master
+  stage: "Data update"
+  when: manual
+  variables:
+    GIT_AUTHOR_EMAIL: 45039513+SocialGroovyBot@users.noreply.github.com
+    GIT_AUTHOR_NAME: Social Groovy Bot
+    GIT_COMMITTER_EMAIL: $GIT_AUTHOR_EMAIL
+    GIT_COMMITTER_NAME: $GIT_AUTHOR_NAME
+    GIT_DEPTH: 4242
+  before_script:
+    - apk update && apk add git jq
+    - git remote set-url origin https://${GH_TOKEN}@github.com/${CI_PROJECT_PATH}.git
+    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
+  script:
+    - yarn config set cache-folder $CI_PROJECT_DIR/.yarn
+    - yarn global add @semantic-release/changelog @semantic-release/exec @semantic-release/git
+      semantic-release
+    - $(yarn global bin)/semantic-release
